set tabstop=4
set softtabstop=4
set shiftwidth=4
set wildmode=longest:full
set wildmenu
set smartindent
set ignorecase smartcase "大小写不敏感，但是同时存在大小写时，则敏感
set hls "查找信息高亮
colorscheme desert "配色
syntax on "语法高亮显示
"set nu "显示行号
"set showmatch "设置匹配模式，类似当输入一个左括号时会匹配相应的右括号
